### ISSUE TITLE
[REQUEST] Create Logo for DireKu

### ISSUE THREAD

**Issue by MichaelCduBois** [MichaelCduBois/DireKu#3]
**Is your feature request related to a problem? Please describe.**
DireKu needs to be noticed by a distinct logo.

**Describe the solution you'd like**
 Currently, the repository uses the default ReactJS logo which can be viewed [here](/Frontend/public/logo512.png). I would like to have a designer create a logo that can be used by the DireKu WebApp.

**Describe alternatives you've considered**
An alternative that I have considered is working on the logo myself, however I believe it would be better for the Open Source community to create the logo for Hacktoberfest.

**Additional context**
Please comment on this issue if you would like to work on it. When submitting the PR, please include the logo in the following sizes and names:

- [x] 512x512 -- logo512.png 
- [x] 192x192 -- logo192.png
- [x] 32x32 -- favicon.ico

In order to be within the spirit of Hacktoberfest, please submit all logos within ONE PR. This should not count for 3 separate PRs. If 3 PRs are submitted, they will be marked as Invalid until combined into one.

**Comment by timothycdykes** [comment]
I've sketched something up, so I guess I'll give it a shot since nobody else has claimed it.

**Comment by MichaelCduBois** [comment]
It has been assigned to you, thanks for helping out!
